### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by vanlueckn** [edbrdi/n8n-nodes-discord#2]
I have installed the package and the discord image is missing:

![MobaXterm_WFgR2NWlRY](https://user-images.githubusercontent.com/53119369/199037290-3aa63480-8bb5-43b3-a78a-5aab72f0423c.png)

![brave_9hFsadQ3dJ](https://user-images.githubusercontent.com/53119369/199037342-caaa9cb0-659b-48fa-9a7a-bdd3f08c9f9a.png)

Version of the package: v0.1.3c
Version of n8n: Version 0.200.1

**Comment by hckdotng** [comment]
How did you install the package? From the community nodes UI? Is it a fresh install or an update?
The path '/home/node/.n8n/nodes/node_modules/n8n-nodes-discord/dist/nodes/Discord' in your logs appears twice, concatenated.

**Comment by vanlueckn** [comment]
I installed it from the community nodes ui. My instance is a fresh install from today.

**Comment by hckdotng** [comment]
This behavior is very strange, I can't reproduce it. On the other hand it makes me think of a similar problem when the node is updated. Can you check the name of the Discord nodes in your database?


Have you installed any other community node and if yes, do you have the same issue?
Can you provide more details on your install (node version, package manager used, Docker/used image...) ?

**Comment by vanlueckn** [comment]
My installed_nodes table:
![heidisql_oTFhg2c2S5](https://user-images.githubusercontent.com/53119369/199108278-142ebade-d5a9-4202-a212-9e7d55a8bacb.png)

I have not installed any other community nodes. 

I use the docker image `n8nio/n8n` (latest version).

**Comment by hckdotng** [comment]
Thanks for the details. I will investigate, but you can fix for now the image by removing the doubled part in the type fields to match the fields in my previous screenshot (but you'll probably need to re-create the nodes in your workflow).

I'm leaving the issue open and will update if I find what's causing this.

**Comment by waaman** [comment]
Hi.
After an update directly from n8n i lost image too.
I run n8n from docker so after the container restart image is now ok.

**Comment by hckdotng** [comment]
Hi, did you have the type field with the name of the package displayed twice (or still have)?
